max-chest-population: 1000
positive-boundary: 99984
negative-boundary: -99984
max-rank-all-item: 5
min-rank-all-item: 2
max-rank-item: 2
min-rank-item: 0
rank:
  Common: 50
  Rare: 25
  Mythical: 20
worlds:
  world: 500
