main: me.hpms.lootworld.LootWorld
name: LootWorld
author: GitHub/hpmss
version: 1.0
description: nani kode
commands:
    lwtest:
         Description: Debugging
         usage: /lwtest
permissions:
    lootworld.god:
         default: op
